### PR TITLE
fix: resolve oauth2_client_id permadiff in backend services

### LINKED ISSUE #25374: `google_compute_backend_service` permadiff for field `iap.oauth2_client_id`
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.7.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v7.12.0
+ provider registry.terraform.io/hashicorp/google-beta v7.12.0

### Affected Resource(s)

`google_compute_backend_service`

### Terraform Configuration

```tf
resource "google_compute_backend_service" "myservice" {
  name            = "myservice"
  backend {
    group = google_compute_region_network_endpoint_group.myservice.id
  }
  iap {
    enabled = true
    # Explicitly not setting oauth2_client_secret
    # Explicitly not setting oauth2_client_id
  }
}

```

### Debug Output

```
  # google_compute_backend_service.superadmin will be updated in-place
  ~ resource "google_compute_backend_service" "myservice" {
        id                                            = "projects/myproject/global/backendServices/myservice"
        name                                          = "my-service"
        # (18 unchanged attributes hidden)
      ~ iap {
          - oauth2_client_id            = " " -> null
            # (2 unchanged attributes hidden)
        }
        # (2 unchanged blocks hidden)
    }
```

### Expected Behavior

There should be no diff

### Actual Behavior

The provider is confusing an empty string and a null value

### Steps to reproduce

1. `terraform apply`

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by muxanasov**
Resolve permadiff for field iap.oauth2_client_id when API returns a single space.

Fixes b/488425726
Fixes https://github.com/hashicorp/terraform-provider-google/issues/25374

```release-note:bug
compute: fixed permadiff for `iap.oauth2_client_id` in `google_compute_backend_service` and `google_compute_region_backend_service` when the API returns a single space
```

### CODE REVIEW

File: tpgtools/templates/serialization.go.tmpl [hunk 1]
```diff
@@ -107,7 +107,7 @@ func ConvertSampleJSONToHCL(product DCLPackageName, resource miscellaneousNameSn
 				{{- end }}
 			{{- end }}
 	default:
-		return "", fmt.Errorf("Error converting sample JSON to HCL: %s not found", product, resource)
+		return "", fmt.Errorf("Error converting sample JSON to HCL: %s/%s not found", product, resource)
```
Comment (shuyama1) [inline tpgtools/templates/serialization.go.tmpl]: Could we remove tpgtools change from this PR? It seems like not related to the fix (?). Correct me if I'm wrong. I believe we recently revert all DCL resources to handwritten https://github.com/GoogleCloudPlatform/magic-modules/pull/16759 and tpgtools will also be removed soon

File: tpgtools/type.go [hunk 2]
```diff
@@ -85,7 +85,7 @@ func (t Type) String() string {
 	case "":
 		return "<nil>"
 	default:
-		return fmt.Sprintf("undefined type: %s", t.typ)
+		return fmt.Sprintf("undefined type: %v", t.typ)
```
Comment (shuyama1) [inline tpgtools/type.go]: Also here. Thanks!

File: tpgtools/templates/serialization.go.tmpl (hunk 1 above)
Comment (muxanasov) [reply tpgtools/templates/serialization.go.tmpl]: Thanks for letting me know! :) That fix was in a response of failing tests, but I also can't see how oauth2_client_id permadiff resolution could lead to those tests to fail.

Anyways, I removed this fix.

File: tpgtools/type.go (hunk 2 above)
Comment (muxanasov) [reply tpgtools/type.go]: done

**Comment by shuyama1** [comment]
The failing tests are unrelated to this change. I'll approve and merge the PR after the current run completes

**Review by shuyama1 — APPROVED** [review]
