### PR TITLE
SuppressDiff when ALL_OBJECTS_ENCRYPTION_ENABLED state is used.

### LINKED ISSUE #26882: google_container_cluster database_encryption state prompts for constant changes
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.14.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v7.26.0

### Affected Resource(s)

google_container_cluster

### Terraform Configuration

```tf
terraform {
  required_version = ">= 1.8"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 7.26.0"
    }
  }
}

provider "google" {
  project = var.test_project
  region  = "us-east1"
}

resource "google_compute_network" "test" {
  name                    = "test-db-encryption-network"
  auto_create_subnetworks = true
}

resource "google_kms_key_ring" "test" {
  name     = "test-db-encryption-keys"
  location = "us-east1"
}

resource "google_kms_crypto_key" "test" {
  name     = "App-Secrets-Key"
  key_ring = google_kms_key_ring.test.id
}

data "google_project" "test" {}

resource "google_kms_crypto_key_iam_member" "gke_service_agent" {
  crypto_key_id = google_kms_crypto_key.test.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:service-${data.google_project.test.number}@container-engine-robot.iam.gserviceaccount.com"
}

resource "google_container_cluster" "test" {
  name                = "test-db-encryption"
  location            = "us-east1-b"
  network             = google_compute_network.test.id
  initial_node_count  = 1
  deletion_protection = false

  database_encryption {
    state    = "ENCRYPTED"
    key_name = google_kms_crypto_key.test.id
  }
}

```

### Debug Output

_No response_

### Expected Behavior

When running plan or apply without changing this configuration, I'd expect the cluster would not need to be updated, as the database_encryption state has not changed.

### Actual Behavior

If I run terraform plan after applying this configuration, it warns me that it will need to update the cluster with
```
~ database_encryption {
          ~ state    = "ALL_OBJECTS_ENCRYPTION_ENABLED" -> "ENCRYPTED"
```

### Steps to reproduce

1. `terraform apply`
2. `terraform plan`
3. Note that the plan proposes an update to the database encryption state, even though no change has been made in the configuration

### Important Factoids

Although looking at the [REST API docs](https://docs.cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster.State) for a cluster shows that the three potential states for database encryption are UNKNOWN, ENCRYPTED, or DECRYPTED, when I query the API for my cluster, it does return that the database state is "ALL_OBJECT_ENCRYPTION_ENABLED". I am wondering if this is an undocumented change in the  projects.locations.clusters API, rather than a provider bug, but I'd still expect the provider to not plan a change for this scenario.

### References

_No response_

b/503368364

### PR DESCRIPTION
**Pull request by loburm**
This PR adds a `DiffSuppressFunc` to the `database_encryption.state` field within the `google_container_cluster` resource. 

Currently, when a user sets the database encryption state to `ENCRYPTED` in their Terraform configuration, the Google Cloud API returns `ALL_OBJECTS_ENCRYPTION_ENABLED` for newer versions of GKE clusters. This discrepancy triggers a continuous diff (permadiff), causing Terraform to attempt an update on every run. This PR suppresses the diff specifically for this scenario, allowing Terraform to recognize that the infrastructure matches the intended configuration.

Fixes https://github.com/hashicorp/terraform-provider-google/issues/26882

```release-note:bug
container: fixed a permadiff in `google_container_cluster` where `database_encryption.state` returning `ALL_OBJECTS_ENCRYPTION_ENABLED` instead of the configured `ENCRYPTED` caused unintended reapplies
```

### CODE REVIEW

File: mmv1/third_party/terraform/services/container/resource_container_cluster_test.go.tmpl [hunk 1]
```diff
@@ -1660,6 +1660,92 @@ resource "google_container_cluster" "managed_ml_diagnostics" {
 {{- end }}
 
 
+func TestAccContainerCluster_withStorageEncryption(t *testing.T) {
```
Comment (shuyama1) [inline mmv1/third_party/terraform/services/container/resource_container_cluster_test.go.tmpl:1663]: I think we can remove this test - We should already have this case covered in test `TestAccContainerCluster_withDatabaseEncryption` which is currently failing due to the `"ALL_OBJECTS_ENCRYPTION_ENABLED" -> "ENCRYPTED"` diff.

File: mmv1/third_party/terraform/services/container/resource_container_cluster.go.tmpl [hunk 2]
```diff
@@ -2361,8 +2361,17 @@ func ResourceContainerCluster() *schema.Resource {
             "state": {
               Type:         schema.TypeString,
               Required:     true,
-              ValidateFunc: validation.StringInSlice([]string{"ENCRYPTED", "DECRYPTED"}, false),
-              Description:  `ENCRYPTED or DECRYPTED.`,
+              ValidateFunc: validation.StringInSlice([]string{"ENCRYPTED", "ALL_OBJECTS_ENCRYPTION_ENABLED", "DECRYPTED"}, false),
+              Description:  `ENCRYPTED, ALL_OBJECTS_ENCRYPTION_ENABLED or DECRYPTED.`,
+              DiffSuppressFunc: func(k, old, new string, d *schema.ResourceData) bool {
```
Comment (shuyama1) [inline mmv1/third_party/terraform/services/container/resource_container_cluster.go.tmpl:2366]: The logic handling the drifts makes sense to me! But could we extract this into a separate function for better readability and testability, such as https://github.com/loburm/magic-modules/blob/aabdded1640a10ceb6014a800aa2776d6081dfa6/mmv1/third_party/terraform/services/container/resource_container_cluster.go.tmpl#L8830

File: mmv1/third_party/terraform/services/container/resource_container_cluster_test.go.tmpl (hunk 1 above)
Comment (loburm) [reply mmv1/third_party/terraform/services/container/resource_container_cluster_test.go.tmpl]: Done.

File: mmv1/third_party/terraform/services/container/resource_container_cluster.go.tmpl (hunk 2 above)
Comment (loburm) [reply mmv1/third_party/terraform/services/container/resource_container_cluster.go.tmpl]: Done.

**Review by shuyama1 — APPROVED** [review]

**Comment by shuyama1** [comment]
The failing tests are unrelated
