### PR TITLE
Fix nightly test failures for external credentials upgrade

### LINKED ISSUE #26748: Failing test(s): TestAccProvider_external_credentials_upgrade
### Impacted tests

TestAccProvider_external_credentials_upgrade

### Affected Resource(s)

google_provider

### Failure rates

- ga: 100%

- beta: 100%

### Message(s)

- [ga error message](https://storage.cloud.google.com/nightly-test-data/test-errors/ga/2026-04-02/TestAccProvider_external_credentials_upgrade-ga-2026-04-02.txt)

- [beta error message](https://storage.cloud.google.com/nightly-test-data/test-errors/beta/2026-04-02/TestAccProvider_external_credentials_upgrade-beta-2026-04-02.txt)

### Test Debug Log

- [ga debug log](https://storage.cloud.google.com/teamcity-logs/nightly/TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS/2026-04-02/48498cc/debug-google-48498cc-640587-TestAccProvider_external_credentials_upgrade.txt)

- [beta debug log](https://storage.cloud.google.com/teamcity-logs/nightly/TerraformProviders_GoogleCloud_GOOGLE_BETA_NIGHTLYTESTS/2026-04-02/a647ee7/debug-google-beta-a647ee7-640642-TestAccProvider_external_credentials_upgrade.txt)

### PR DESCRIPTION
**Pull request by shuyama1**
fixes https://github.com/hashicorp/terraform-provider-google/issues/26748

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:none

```

### CODE REVIEW

**Comment by shuyama1** [comment]
/gcbrun

failed during token rotation

**Comment by shuyama1** [comment]
Test passed on [TC](https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_PROVIDER/645646?buildTab=tests)

File: mmv1/third_party/terraform/provider/provider_test.go.tmpl [hunk 1]
```diff
@@ -223,19 +224,17 @@ func TestAccProvider_external_credentials_upgrade(t *testing.T) {
...
 				},
 				Config: testAccProviderExternalCredentialsUpgrade_CredentialsConfig(map[string]interface{}{
-					"credentials": credentials,
+					"credentials": strconv.Quote(credentials),
 				}),
-				Check: resource.ComposeTestCheckFunc(
-					resource.TestCheckResourceAttr("data.google_provider_config_sdk.default", "credentials", credentials),
-				),
+				// google_provider_config_sdk is not available in 6.10.0, so we cannot verify credentials here.
+				// The fact that this step succeeds implies the provider accepted the credentials.
```
Comment (BBBmau) [inline mmv1/third_party/terraform/provider/provider_test.go.tmpl:237]: im not sure i follow, the first step uses the old version while also following the config apply with a checkAttribute on `data.google_provider_config_sdk.default`

https://github.com/shuyama1/magic-modules/blob/0c3476b87bc6e640419a1edf7d39fce9fa36c62e/mmv1/third_party/terraform/provider/provider_test.go.tmpl#L206-L209

so we should be able to leave the check step here. removing the need for `testAccProviderExternalCredentialsUpgrade_CredentialsConfigNew` also

**Review by BBBmau — COMMENTED** [review]
looks good, the changes make sense in the context of the plugin-testing changes introduced in `1.14.1` just a minoir quesiton on the removal of a check step

File: mmv1/third_party/terraform/provider/provider_test.go.tmpl [hunk 2]
```diff
@@ -223,19 +224,17 @@ func TestAccProvider_external_credentials_upgrade(t *testing.T) {
...
 					}
 				},
 				Config: testAccProviderExternalCredentialsUpgrade_CredentialsConfig(map[string]interface{}{
-					"credentials": credentials,
+					"credentials": strconv.Quote(credentials),
 				}),
-				Check: resource.ComposeTestCheckFunc(
-					resource.TestCheckResourceAttr("data.google_provider_config_sdk.default", "credentials", credentials),
-				),
+				// google_provider_config_sdk is not available in 6.10.0, so we cannot verify credentials here.
```
Comment (shuyama1) [inline mmv1/third_party/terraform/provider/provider_test.go.tmpl]:
```suggestion
				// google_provider_config_sdk is test-specific datasource
				// not available in the real provider, so we cannot verify credentials here.
```

File: mmv1/third_party/terraform/provider/provider_test.go.tmpl (hunk 1 above)
Comment (shuyama1) [reply mmv1/third_party/terraform/provider/provider_test.go.tmpl:237]: The issue is that we can't use `google_provider_config_sdk` datasource with the real provider. It's a test-specific data source, not publicly available testhttps://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/acctest/vcr_utils.go#L392

Therefore, need to remove it from `testAccProviderExternalCredentialsUpgrade_CredentialsConfig` and add the new `testAccProviderExternalCredentialsUpgrade_CredentialsConfigNew` to include it, so we can check that in step 4

File: mmv1/third_party/terraform/provider/provider_test.go.tmpl [hunk 3]
```diff
@@ -180,7 +181,7 @@ func TestAccProvider_external_credentials_upgrade(t *testing.T) {
 	}
 
 	accessToken := acctest.GetAccessTokenFromTestCredsFromEnv(t)
-	credentials := transport_tpg.TestFakeCredentialsPath
+	credentials := acctest.GenerateFakeCredentialsJson("test")
```
Comment (BBBmau) [inline mmv1/third_party/terraform/provider/provider_test.go.tmpl]: this change isn't necessary since we can resolve the JSON validation errors by updating {{context}} to be in quotes:

https://github.com/GoogleCloudPlatform/magic-modules/pull/17063/changes/BASE..0c3476b87bc6e640419a1edf7d39fce9fa36c62e#diff-f588738c13fa01d362fcd98372c66fbf1db8744507eb9f85ea5490ebf05795a7L269-R279

File: mmv1/third_party/terraform/provider/provider_test.go.tmpl (hunk 1 above)
Comment (BBBmau) [reply mmv1/third_party/terraform/provider/provider_test.go.tmpl:237]: This makes sense why it started failing, there's conflicts now when setting both `ExternalProviders` and `ProviderFactories` so removing `ProviderFactories` resulted in us not being able to leave the TestCheck using the `google_provider_config_sdk` data_source

**Review by BBBmau — CHANGES_REQUESTED** [review]
did some manual runs and there's some changes that we don't need to resolve the failing nightly test

File: mmv1/third_party/terraform/provider/provider_test.go.tmpl (hunk 3 above)
Comment (shuyama1) [reply mmv1/third_party/terraform/provider/provider_test.go.tmpl]: Good catch. Updating!

Comment (shuyama1) [reply mmv1/third_party/terraform/provider/provider_test.go.tmpl]: Reverted this change! Thanks!

**Comment by shuyama1** [comment]
Run tests on [TC](https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_PROVIDER/647598)

File: mmv1/third_party/terraform/provider/provider_test.go.tmpl [hunk 4]
```diff
@@ -4,6 +4,7 @@ import (
 	"fmt"
 	"regexp"
 	"os"
+	"strconv"
```
Comment (BBBmau) [inline mmv1/third_party/terraform/provider/provider_test.go.tmpl]:
```suggestion
```

File: mmv1/third_party/terraform/provider/provider_test.go.tmpl [hunk 5]
```diff
@@ -245,8 +245,8 @@ func TestAccProvider_external_credentials_upgrade(t *testing.T) {
 						t.Setenv(env, "")
 					}
 				},
-				Config: testAccProviderExternalCredentialsUpgrade_CredentialsConfig(map[string]interface{}{
-					"credentials": credentials,
+				Config: testAccProviderExternalCredentialsUpgrade_CredentialsConfigNew(map[string]interface{}{
+					"credentials": strconv.Quote(credentials),
```
Comment (BBBmau) [inline mmv1/third_party/terraform/provider/provider_test.go.tmpl]:
```suggestion
					"credentials": credentials,
```

File: mmv1/third_party/terraform/provider/provider_test.go.tmpl [hunk 6]
```diff
@@ -269,7 +269,15 @@ data "google_client_config" "default" {}
 func testAccProviderExternalCredentialsUpgrade_CredentialsConfig(context map[string]interface{}) string {
 	return acctest.Nprintf(`
 provider "google" {
-  credentials = "%{credentials}"
+  credentials = %{credentials}
```
Comment (BBBmau) [inline mmv1/third_party/terraform/provider/provider_test.go.tmpl]:
```suggestion
  credentials = "%{credentials}"
```

File: mmv1/third_party/terraform/provider/provider_test.go.tmpl [hunk 7]
```diff
@@ -269,7 +269,15 @@ data "google_client_config" "default" {}
...
+}
+`, context)
+}
+
+func testAccProviderExternalCredentialsUpgrade_CredentialsConfigNew(context map[string]interface{}) string {
+	return acctest.Nprintf(`
+provider "google" {
+  credentials = %{credentials}
```
Comment (BBBmau) [inline mmv1/third_party/terraform/provider/provider_test.go.tmpl]:
```suggestion
  credentials = "%{credentials}"
```

File: mmv1/third_party/terraform/provider/provider_test.go.tmpl [hunk 8]
```diff
@@ -223,19 +224,18 @@ func TestAccProvider_external_credentials_upgrade(t *testing.T) {
...
-				ExternalProviders:        oldVersion,
+				ExternalProviders: oldVersion,
 				PreConfig: func() {
 					for _, env := range envvar.CredsEnvVars {
 						t.Setenv(env, "")
 					}
 				},
 				Config: testAccProviderExternalCredentialsUpgrade_CredentialsConfig(map[string]interface{}{
-					"credentials": credentials,
+					"credentials": strconv.Quote(credentials),
```
Comment (BBBmau) [inline mmv1/third_party/terraform/provider/provider_test.go.tmpl]:
```suggestion
					"credentials": credentials,
```

**Review by BBBmau — COMMENTED** [review]
adding the quotations in the test config allows us to not need the `strconv` import

**Review by BBBmau — APPROVED** [review]

**Comment by shuyama1** [comment]
@BBBmau Thanks!

**Comment by shuyama1** [comment]
New TC [run](https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_PROVIDER/647606)
