### PR TITLE
fix: (storage) fix inconsistent plan issue for `custome_attributes` field

### LINKED ISSUE #26804: google_storage_notification returns inconsistent custom_attributes after apply
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform >= 1.3.0, < 2.0.0
+ provider registry.terraform.io/hashicorp/google v7.x
+ provider registry.terraform.io/hashicorp/google-beta v7.x

### Affected Resource(s)

google_storage_notification

### Terraform Configuration

```
resource "google_storage_notification" "example" {
  bucket         = google_storage_bucket.example.name
  topic          = google_pubsub_topic.example.id
  payload_format = "JSON_API_V1"

  # custom_attributes omitted
}

```

### Debug Output

_No response_

### Expected Behavior

custom_attributes defaults to an empty map.

When the argument is omitted (or explicitly set to {}),the provider should return an empty map consistently
before and after apply, and Terraform should complete the apply successfully without detecting a state mismatch.

### Actual Behavior

Terraform plans custom_attributes as an empty map.
After apply, the provider returns custom_attributes as null.

This results in the following error:

"Provider produced inconsistent result after apply:
.custom_attributes: was cty.MapValEmpty(cty.String), but now null."

### Steps to reproduce

1. Define a google_storage_notification resource with custom_attributes omitted
2. Run terraform init
3. Run terraform apply
4. Terraform fails with "Provider produced inconsistent result after apply"

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by gurusai-voleti**
**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/26804
```release-note:bug
storage: fix inconsistent plan issue for `custome_attributes` field
```

### CODE REVIEW

**Review by googlyrahman — APPROVED** [review]

**Review by roaks3 — APPROVED** [review]

**Comment by roaks3** [comment]
From a teammate:

> this looks like a case where the inconsistency on plan can be resolved with a planModifier
> 
> https://developer.hashicorp.com/terraform/plugin/framework/resources/plan-modification#attribute-plan-modification

**Comment by gurusai-voleti** [comment]
> From a teammate:
> 
> > this looks like a case where the inconsistency on plan can be resolved with a planModifier
> > https://developer.hashicorp.com/terraform/plugin/framework/resources/plan-modification#attribute-plan-modification

after adding planmodifiers also, when running tf plan/apply shows changes even no change is required and this is not fully solving the issues

the change provided in the PR is sufficient to solve the issue, please let me know your point of view

**Comment by roaks3** [comment]
I think the suggestion is to use plan modifiers as the more idiomatic approach, unless there is an issue with doing so. Otherwise, we end up with a proliferation of custom solutions, which is far more difficult to maintain.

Could you share any more about what you tried and what did not work?

Looping in @BBBmau who has more expertise with the framework.

File: mmv1/third_party/terraform/services/storage/fw_resource_storage_notification.go [hunk 1]
```diff
@@ -308,9 +309,22 @@ func (r *storageNotificationResource) refresh(ctx context.Context, model *storag
...
+			model.CustomAttributes = emptyMap
+		} else {
+			model.CustomAttributes = types.MapNull(types.StringType)
+		}
+	} else {
+		// API returned actual values, so we map them normally
+		var customAttrsDiags diag.Diagnostics
+		model.CustomAttributes, customAttrsDiags = types.MapValueFrom(ctx, types.StringType, res.CustomAttributes)
+		diags.Append(customAttrsDiags...)
+	}
```
Comment (BBBmau) [inline mmv1/third_party/terraform/services/storage/fw_resource_storage_notification.go:327]: after going through the changes, this is the correct implementation since a modifyPlan requires checking the values between current state and expected change.

Going from `{}` -> `null` isn't exactly possible since it causes a type mismatch:
```hcl
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/hashicorp/google" planned an invalid value for google_storage_notification.notification.custom_attributes: planned value cty.NullVal(cty.Map(cty.String))
│ does not match config value cty.MapValEmpty(cty.String).
```

Though i question whether we want to do this at all. Having this included results in a force change when explicitly setting `custom_attributes = {}` when `"custom_attributes": null`

```hcl
Terraform will perform the following actions:

  # google_storage_notification.notification must be replaced
-/+ resource "google_storage_notification" "notification" {
      + custom_attributes = {} # forces replacement
      ~ id                = "testing-custom-attributes/notificationConfigs/33" -> (known after apply)
      ~ notification_id   = "33" -> (known after apply)
      ~ self_link         = "https://www.googleapis.com/storage/v1/b/testing-custom-attributes/notificationConfigs/33" -> (known after apply)
        # (4 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

Not merging this would keep the inconsistent apply which prevents this from being recreated. Though I also noticed that the state gets tainted due to the destroy step being completed followed by recreation which is where we then experience the inconsistent result after apply.

I've attempted to look for any patches that can be done we prevent the force recreation when going from `{} -> null` in state but it looks to be a limitation in framework.

Since the force recreation is already a behavior that is present on this behavior we can move forward with this fix for the `inconsistent result after apply`. 

cc: @roaks3 I'll open a issue on plugin-framework to see if there's something that can be done to resolve this specific diff case.

**Review by BBBmau — APPROVED** [review]

**Review by roaks3 — APPROVED** [review]
Thanks @BBBmau !
